name = "Hydrology"
uuid = "91547ff3-b885-4d35-ac59-f1ca93abc87d"
authors = ["Takis Angelides"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
